drop table if exists `COMMON_MESSAGE`;
CREATE TABLE `COMMON_MESSAGE` (
  `MESSAGE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `MESSAGE_NAME` varchar(100) NOT NULL,
  `MESSAGE_CONTENT` varchar(100) NOT NULL,
  `MESSAGE_STATUS` varchar(1) NOT NULL,
  `MESSAGE_CREATE_DATE_TIME` timestamp NULL,
  `MESSAGE_UPDATE_DATE_TIME` timestamp NULL,
  PRIMARY KEY (`MESSAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
