insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (1,"name1", "content1", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (2,"name2", "content2", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (3,"name3", "content3", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (4,"name4", "content4", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (5,"name5", "content5", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (6,"name6", "content6", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (7,"name7", "content7", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (8,"name8", "content8", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (9,"name9", "content9", "N", NOW());
insert into COMMON_MESSAGE(MESSAGE_ID,MESSAGE_NAME, MESSAGE_CONTENT, MESSAGE_STATUS, MESSAGE_CREATE_DATE_TIME) values (10,"name10", "content10", "N", NOW());

